<?php

namespace App\Enums;

enum AuditAction: string
{
    case CREATED = 'CREATED';
    case UPDATED = 'UPDATED';
    case DELETED = 'DELETED';
    case REQUEST_SUBMITTED = 'REQUEST_SUBMITTED';
    case REQUEST_ACCEPTED = 'REQUEST_ACCEPTED';
    case REQUEST_REJECTED = 'REQUEST_REJECTED';
    case REQUEST_RESET = 'REQUEST_RESET';
    case OCCUPATION_STARTED = 'OCCUPATION_STARTED';
    case OCCUPATION_ENDED = 'OCCUPATION_ENDED';
    case VACATION_RECORDED = 'VACATION_RECORDED';
    case DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED';
    case DOCUMENT_DELETED = 'DOCUMENT_DELETED';
}
